FROM node:lts-alpine3.9
WORKDIR /app
COPY --from=corleykennard/cloud-drive:dev /app/public ./public
COPY --from=corleykennard/cloud-drive:dev /app/package.json .
RUN npm i -g sirv-cli
EXPOSE 5000
ENTRYPOINT ["sirv", "public"]